services:
  mermaid-renderer:
    build: .
    image: ghcr.io/erik-balfe/mermaid-renderer:latest
    ports:
      - "3022:3022"
    environment:
      - PORT=3022
      - RATE_LIMIT_WINDOW=60000
      - MAX_REQUESTS=60
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3022/health"]
      interval: 30s
      timeout: 10s
      retries: 3
